version: '3.5'

services:

  app:
    container_name: react-cli
    build:
      context: .
      dockerfile: Dockerfile-React-CLI
    volumes:
      - '.:/opt/app'
      - '/opt/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development